### ISSUE TITLE
论坛搭建

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/old.juliacn.github.io#2]
@GaZ3ll3 提到了https://github.com/RocketChat/Rocket.Chat

服务器的问题我可以去联系一下，但是现在的人手似乎还有点少，我们也许先把主页做起来再议？

**Comment by GaZ3ll3** [comment]
主页静态网页就足够了. 个人觉得要是host在github上, 就jekyll.

如果要做通讯群组的话, 毕竟国内不太方便, 我看着觉得Rocket还可以, 可以用docker搭建, 拿少年班的node做都可以, 只是负载和database有限.

**Comment by Roger-luo** [comment]
@GaZ3ll3 lug这边可以提供技术支持(比如修漏洞)，也可以提供服务器，但是国内建站的话需要备案。科大lug的论坛采用的策略是把论坛放在国外，然后反代回来。@gaoyifan

张老师那边表示可以和ijuco放在一起(意思应该是一台服务器上?),还可以提供域名

**Comment by gaoyifan** [comment]
服务器放在国内是考虑到数据的可控性。国外反代是想规避政策风险。 @Roger-luo 
如果能给域名备个案，那就可以直接解析到科大了。

**Comment by KDr2** [comment]
简单静态页面或者 fcgi 程序的话，我这边也有服务器可以用, dreamhost, 国外。
技术支持我这边也可以提供，对这块还算比较熟 :)

**Comment by gaoyifan** [comment]
USTC Linux User Group这边提供的是vSphere虚拟机，虚拟机级别的每日异地机房备份，提供系统root权限。国外接入点（东京机房）的反向代理配置需要联系 @ustclug 修改。

**Comment by sfchen** [comment]
已经搭了一个简单的 http://julia.org.cn    ，而且已经做完备案，服务器由用Julia处理基因数据的haplox赞助了，现在里面有文档的链接，各种群的二维码。
后期会把这些丰富起来，大家多出谋划策

**Comment by Roger-luo** [comment]
@sfchen 不知道如果愿意贡献内容是否有什么平台或者接口？

**Comment by sfchen** [comment]
@Roger-luo 可以用个内容管理系统，wordpress等什么都可以，这样大家可以往里面贴内容

**Comment by Roger-luo** [comment]
也许可以考虑在这个服务器上把论坛搭起来？不过不知道论坛的形式怎么样比较好。

**Comment by GaZ3ll3** [comment]
现在论坛的搭建是要像stackoverflow的Q&A还是普通论坛 https://discuss.flarum.org/ 这样的？还是在segmentfault上弄个topic就足够？

update: wordpress有几款插件可以做成Q&A，现在来看是最稳定最直接的办法。wecenter的配置我自己的机器跑不起来，gd在linux上安装略复杂。

**Comment by Roger-luo** [comment]
由于已经有了问答社区 [Julia.org.cn](http://julia.org.cn), 所以暂时将这个issue关闭了
