### ISSUE TITLE
repo名需要改？

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/old.juliacn.github.io#3]
@KDr2 我们主页服务器是用GitHub吗？这样似乎需要将repo名写为name.github.io的形式

https://pages.github.com/

**Comment by KDr2** [comment]
用 github pages 可以啊，我来改名吧。 改名后就算不用 github pages 也不影响 :)

**Comment by KDr2** [comment]
已经该好了，新建了一个 index.html 作为测试，http://juliacn.github.io/ 已经能看到，如果决定使用 Jekyll 的话，直接 push Jekyll 的目录就行了，如果使用其他的 github 不直接支持的 static page generator 的话，就把源文件和编译输出都提交了吧，源文件放某子目录，编译输出目录设置此项目根目录就可以了。

目前貌似没有 Julia 写的 static page generator。

**Comment by KDr2** [comment]
我初始化了 Jekyll 项目并 push 了， 我比较喜欢 Dapper(https://github.com/markdbenson/dapper), 但是 Jekyll 比较 popular, 而且 Github 直接支持，不用提交编译输出的 html 文件。Dapper 使用起来相对简单。大家可以先试试熟悉一下。

**Comment by Roger-luo** [comment]
OK.本来也想说Jekyll来着，已经开始看了。社区图标的事情还没有回复我，所以也可以暂时先像tokyo一样在下面打几个字:Julia China这种.

**Comment by i2000s** [comment]
图标或许可以直接加上中文毛笔效果的“中国”二字。Julia的图标已开源，我们可以直接用，属于fair use。

**Comment by GaZ3ll3** [comment]
我用latex写了个简单的.

https://www.sharelatex.com/project/56352e6e294753ac3f010de1
![logo2_1](https://cloud.githubusercontent.com/assets/1414789/10866801/ce8cf556-800f-11e5-83cc-2b5fbb88cf02.png)
![logo1_1](https://cloud.githubusercontent.com/assets/1414789/10866802/ce8d92a4-800f-11e5-8274-080dcf1c5ed1.png)

China的颜色字体可以再斟酌, 还有间距什么的. 图是截图的, size暂时为 650 x 200

**Comment by i2000s** [comment]
名字可以。

@GaZ3ll3 Julia的字体官方使用Sinhala MN Bold，在Mac OS上有。颜色黑底为[37,37,37,255] RGB参数。

我用Inkscape做了几个中文的效果方案。原字体部分来自叶根友毛笔行书字体的拼接，后经艺术加工而成：

![juliacn_1](https://cloud.githubusercontent.com/assets/3915003/10866715/0b7f1546-8003-11e5-81ac-13b1952fad29.png)
![juliacn_1](https://cloud.githubusercontent.com/assets/3915003/10867173/ed10516c-8019-11e5-8cb6-e6ab382c9d3f.png)

![juliacn_2](https://cloud.githubusercontent.com/assets/3915003/10867174/f514d176-8019-11e5-8324-01ef4af32a12.png)

SVG源文件见[百度云链接](http://pan.baidu.com/s/1pJu1nQj)， 密码：2ib9
如果觉得可行，大家可以继续在源文件基础上继续加工，以用于本站建设。

**Comment by GaZ3ll3** [comment]
julia中文不好，要不就写julia中文社区，julia中国可以。

style需要大家再斟酌下，可以写成左右也可以上下，官方的logo也不一定非要使用进来。个人觉得作为一个logo要以简洁明快为主(比如只用那四个点代表Julia)，不必复杂，网站的identity靠title就可以了。

**Comment by Roger-luo** [comment]
@i2000s 我觉得Julia中国很赞，不过中国里面为啥是黄的....用Julia的i上面的那个红色也许更好？

因为中国的话红色可能更好一些，然后同时也与Julia的风格相同

然后style的话我觉得上下会好一些，横着长宽比显得太长不好看了。

**Comment by i2000s** [comment]
个人倾向于**_Julia中文**_，强调交流的语言文化背景，而非地域限制。用**_Julia中国**_或许会让一些华人不舒服。之所以没有用“中文社区”，是因为这个logo可以放到很多场合下组成新的名词，比如**_Julia中文频道**_对应视频汇总，**_Julia中文论坛**_、**_Julia中文手册**_、**_Julia中文群**_、**_Julia中文会谈**_等等。主体logo加上这些关键词作为脚标可以方便生成衍生图标，醒目而主题明确。倘若把“中文”替换成“中国”，恐怕就显得有些狭隘，很难对众多场景达到同样的效果了，而且里面的一点比例很难放大到跟其他部分协调的程度。不过**_中文**_二字字体上，我手改的比较粗略，大家有兴趣的话可以继续优化下。

彩色部分以五星红旗的二元主色生成，这也是中华传统文化里表示喜庆、收获和财富的颜色，具有动感和火热的意象，配合原Julia的几个偏冷的色调，形成冷热动静的均衡，象征着中文活动的加入对Julia的发展增添辉煌的色彩和不凡的活力，反之亦然。我曾是用过红色，结果第一反应是流血的意象，而且跟其他几个圆有重叠，这个style或许日本人会用。

除了这个矩形的文字图标外，可以再设计个偏方形的简洁版图形logo。可以直接使用**_中**_字，其组成的三划用Julia里面三个圆的颜色着色。紫为侧影，从东而来；红为胸领，环抱三边，就像条红领巾、红丝带；绿为主干，风华正茂。每一部分内部和外围着色跟几个圆点类似，但是外围部分的着色或许可以采用互补的模式，内外形成一定的阴影错落（就像**_文**_字上面的那一点的效果），可以达到方块汉字书法特有的立体和动态效果。有时间的同仁可以试试看。两类图标可以在不同的环境下使用，与[JuliaQuantum组织](http://juliaquantum.github.io/)的一简一繁、一图一字两个图标的设计目标一致。后面的详细设计我估计就没时间做了。

**Comment by GaZ3ll3** [comment]
作为一个logo来说, julia中文也过长, julia中国也是.

作为title, 这个title如需要表达一个中文站汇总的意思, 那用中文确实没问题, 要考虑的是仅仅一个Julia中文是不是足够, 是不是可以让别人立刻明白. 

julia中国 重点在于开展的各种活动面向的是国内的人, 不必要非得使用中文交流. 

logo见仁见智, 只要把Julia的几种颜色表达出来即可.

**Comment by Roger-luo** [comment]
我觉得主页logo Julia中文就好，但是@i2000s 的 文 可能还需要修改，这个配色与Julia的配色不搭，太突出了。

短小的logo直接用那三个点就好。

**Comment by i2000s** [comment]
repo的名字应该可以暂时用这个，原来文档的域名可以mask到这个主站上，文档连接到主站。

logo如果有争议可以等待汇集到足够的人才之后再行讨论，不必纠结。我提供的素材svg源文件也在网路上，大家可以自由更改。字的笔画都是可以在inkscape等软件里一点点的拖拽而成，应该很容易改，就是要花些时间和耐心。当前应当集中力量以站点为信息汇总的桥梁，把人才引进来。通过一段时间的民主互动，选拔推荐在各个方面更加优秀的带头人，让有能力团结更多人的领导者和有远见卓识品质的号召者发挥其作用，带领大家优先向有光明前景的发展方向前进，建立健全发展机制，以发展人才队伍和用户群组为重点、推陈出新、民主集中、务实攻关，我想这样已经是成功了一半了，也是开源社区从无序到有序的必经之路。

@GaZ3ll3 @Roger-luo @KDr2 特别感谢以上诸位发起对中文站点的建设工作。

**Comment by Roger-luo** [comment]
关于社区标志另外开一个issue吧，repo名就先这么定啦。
