### ISSUE TITLE
JetAlpha 来啦！

### ISSUE THREAD

**Issue by KDr2** [JuliaCN/old.juliacn.github.io#7]
Hi, All
我发起了一个项目，叫做 JetAlpha, 最初目的是使用 Julia 做个玩具或者试验场，让大家一起开发一起玩，什么功能都可以加上，第一步我做了一个 bot 放到 pubu.im 上，可以算算术，查文档。

昨天又来这里看讨论，发现这边讨论的大部分事情都没有进展，于是我就想在 JetAlpha 里把这边的一些事情也放进去，于是就这样了： http://jetalpha.kdr2.com/

JetAlpha 目前的特点和功能：
- 使用 Julia 开发
- 支持 pubu/slack 的机器人
- 一个简单的 FrontPage

目前计划中的功能：
- 支持 Markdown 动态渲染，跟其他静态页面生成器一样只需书写 md 就可以看到页面
- 支持 Mustache 模板，可以使用 Julia 做一些动态内容 (比如论坛这样的，当然我可能不会把论坛做到里面)
-  @Roger-luo 说他会给 bot 加语义分析
- 在通过 web/bot 运行一些 julia 代码

发到这里一是宣传一下希望更多人参与，再就是不知道对于我把 frontpage 作为首页，大家什么意见。

@i2000s @Roger-luo @adousen  @GaZ3ll3 @gaoyifan

**Comment by xianyi** [comment]
果然很有趣

**Comment by Roger-luo** [comment]
@KDr2 要不要把Jet的repo clone到JuliaCN一份? 然后后面可以把这个jekyll换成你的这个?

**Comment by KDr2** [comment]
@Roger-luo 我觉得可以
1. 依我个人的意愿，我更愿意看到社区在网络上的存在是 Julia 驱动的（或说是由 julia 实现的），社区也能在过程中学习体验 Julia，而且在宣传方面也有噱头。当然这只是我个人的想法。
2. 如果大家赞同，我觉得需要做的就是：
   a. 根据域名来分发页面：http://jetalpha.org 是 jetalpha 的主页，http://juliacn.org 是 juliacn 的主页，这个应该很简单。mex做个 branch 就好了。
   b. 把 jetalpha 里面的 markdown 渲染加上 css，有了这个以后，页面能看了，大家贡献内容就方便了，直接写 md 提交，就能看到，这个功能的现状是：能把 md 转成 html，但是没有 css，比如 https://github.com/KDr2/JetAlpha.jl/blob/master/data/markdown/test.md 可以通过 http://jetalpha.org/md/test 来看
3. 只要上面这两个完成了，就可以大力鼓吹和吸引大家使用 julia 来添砖加瓦了。

如果大家都觉得可以的话，可以把 a b 在 jetalpha 里建成 issue :)
另：我这个月实在是太忙了……不好意思。

**Comment by KDr2** [comment]
a 已经实现：

http://juliacn.com/ 是社区首页
http://jetalpha.org/ 是 jetalpha 首页

他们是同一个进程里的。

https://github.com/KDr2/JetAlpha.jl/commit/c988b94253ea5422f65e1ef1e0be58ffd557e620

**Comment by Roger-luo** [comment]
@KDr2 同意， 但是因为临近的meetup活动， 还是急需一个入口， 以及报名表改成金数据了....然后感觉现在juliacn.github.io的css可能更漂亮一点？（可能我个人比较喜欢极简的吧，不过现在不知道为啥这个pages上不去了）不知道能不能复制过来？我觉得我们可以慢慢把juliacn.github.io下面全部换成julia驱动的。
